"""
evaluate_item_analysis.py
=========================
How reliably does the quiz question analysis find problems that are known to be there?

It simulates many classes (seed_demo.simulate_class) taking nine questions with planted patterns, then checks
what rag_core.item_analysis reports against the planted truth. For each class size it prints:

  misconception found     - of the planted misconceptions, how many were reported (and with the right wrong option)
  false misconceptions    - reports on questions that had no planted misconception, per class
  faulty key found        - of the planted faulty keys, how many were flagged "Check the answer key"
  false key alarms        - flags on questions whose key was fine, per class

Read it with care: the students are generated by a simple model written by the project authors, so this shows
how the method behaves when the effects are the size we assumed, not how it behaves on real students. The
thresholds in item_analysis.py were set after looking at simulated classes of 24, so the 24 row is the least
independent one.

Usage:  python evaluate_item_analysis.py [classes_per_size]
"""

import sys

from rag_core.item_analysis import FLAG_CHECK_KEY, analyze_quizzes
from seed_demo import simulate_class


def make_quizzes(n_quizzes: int = 3, per_quiz: int = 3):
    return [
        {
            "id": q + 1, "topic": f"Topic {q + 1}",
            "questions": [
                {"question": f"Q{i + 1}?", "options": ["right", "wrong-a", "wrong-b", "wrong-c"], "answer_index": 0}
                for i in range(per_quiz)
            ],
        }
        for q in range(n_quizzes)
    ]


def evaluate(size: int, classes: int) -> dict:
    found = planted = wrong_option_right = false_misc = 0
    keys_found = keys_planted = false_keys = 0
    for seed in range(classes):
        quizzes = make_quizzes()
        plan, attempts = simulate_class(quizzes, size, seed)
        stats = {(q.quiz_id, q.number): q for a in analyze_quizzes(quizzes, attempts) for q in a.questions}
        for quiz, number, _q, kind, popular_wrong in plan:
            stat = stats.get((quiz["id"], number))
            if kind == "misconception":
                planted += 1
                if stat and stat.misconception:
                    found += 1
                    wrong_option_right += int(stat.misconception.index == popular_wrong)
            elif stat and stat.misconception:
                false_misc += 1
            if kind == "faulty key":
                keys_planted += 1
                keys_found += int(bool(stat) and FLAG_CHECK_KEY in stat.flags)
            elif stat and FLAG_CHECK_KEY in stat.flags:
                false_keys += 1
    return {
        "size": size, "classes": classes,
        "misconception found": f"{found}/{planted}", "right option": f"{wrong_option_right}/{found or 1}",
        "false misconceptions per class": false_misc / classes,
        "faulty key found": f"{keys_found}/{keys_planted}", "false key alarms per class": false_keys / classes,
    }


def main() -> None:
    classes = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    rows = [evaluate(size, classes) for size in (8, 12, 24, 48, 100)]
    headers = list(rows[0])
    print(" | ".join(f"{h}" for h in headers))
    for row in rows:
        print(" | ".join(f"{row[h]:.3f}" if isinstance(row[h], float) else str(row[h]) for h in headers))


if __name__ == "__main__":
    main()
