"""
evaluate_confusion.py
=====================
Does the Concept Confusion score find the concepts that are really confusing, better than simpler rules?

It simulates many classes of 8 concepts in which 2 are planted as truly confusing, 1 is planted as merely
POPULAR (many students ask about it out of curiosity, but they are not confused), and the rest are ordinary.
Each method then ranks the concepts and is scored by:

  precision@2     of its top 2 concepts, how many are truly confusing (1.00 is perfect; chance is about 0.25)
  popular in top2 how often the merely popular concept lands in its top 2 (lower is better)

Methods:
  question count      rank by number of questions (what grouping questions by topic alone suggests)
  unique students     rank by number of different students who asked (the "40 students asked" idea)
  quiz only           rank by the class quiz miss rate
  composite           the Concept Confusion score with its default weights
  composite, no quiz  the same without the quiz signal (for a class that has taken no quiz yet)

READ THIS BEFORE QUOTING ANY NUMBER: the students are generated by a model written by the project authors.
Confusion is made to cause more follow-ups, explanation requests, repeat days and quiz misses, and "popular"
is made to cause many one-off questions. The test therefore shows that, IF real students behave roughly like
that, combining signals beats counting questions, and how much data and how strong an effect the method
needs. It does not show that real students behave like that. Only a real class can.

Usage:  python evaluate_confusion.py [classes_per_setting]
"""

import random
import sys
from types import SimpleNamespace

from rag_core.confusion import DEFAULT_WEIGHTS, compute_confusion
from rag_core.oral_assessment import LEVEL_DEVELOPING, LEVEL_STRONG

CONCEPTS = 8
CONFUSING = 2
TOP = 2


def simulate(size: int, strength: float, seed: int, quiz_rate: float = 0.8):
    """One simulated class. Returns (rows, quizzes, attempts, oral, confusing_names, popular_name)."""
    rng = random.Random(seed)
    order = list(range(CONCEPTS))
    rng.shuffle(order)
    confusing, popular = set(order[:CONFUSING]), order[CONFUSING]
    names = [f"Concept {j} Topic" for j in range(CONCEPTS)]

    rows, attempts, oral = [], [], []
    quizzes = [{"id": j + 1, "topic": names[j], "scope": "class", "questions": []} for j in range(CONCEPTS)]
    for s in range(size):
        student = f"student-{s}"
        for j in range(CONCEPTS):
            c = 1.0 if j in confusing else 0.0
            p_ask = 0.70 if j == popular else 0.20 + 0.15 * strength * c + (0.15 * c)
            if rng.random() < p_ask:
                day = rng.randint(0, 1 + int(3 * strength * c))
                follow_p, explain_p = 0.05 + 0.50 * strength * c, 0.05 + 0.30 * strength * c
                n_questions = 1 + (rng.random() < follow_p)
                for k in range(n_questions):
                    rows.append({
                        "id": len(rows) + 1, "student_id": student, "session_id": f"{student}-d{day}",
                        "asked_at": f"2026-10-{day + 1:02d}T10:{k * 3:02d}:00+00:00",
                        "agent": "Concept Explainer" if rng.random() < explain_p else "Doubt Resolver",
                        "follow_up_of": 1 if k else None,
                        "retrieved": [{"source": "notes.pdf", "page": j, "section": names[j]}],
                    })
            if rng.random() < quiz_rate:
                right = sum(rng.random() < 0.75 - 0.40 * strength * c for _ in range(4))
                attempts.append({"id": len(attempts) + 1, "student_id": student, "quiz_id": j + 1, "topic": names[j],
                                 "correct": right, "total": 4, "answers": []})
            if rng.random() < 0.25:
                weak = rng.random() < 0.20 + 0.45 * strength * c
                oral.append(SimpleNamespace(id=len(oral) + 1, student_id=student, topic=names[j],
                                            understanding_level=LEVEL_DEVELOPING if weak else LEVEL_STRONG))
    return rows, quizzes, attempts, oral, {names[j] for j in confusing}, names[popular]


def rankings(rows, quizzes, attempts, oral, rng):
    """Concept names, best guess first, for each method."""
    names = [f"Concept {j} Topic" for j in range(CONCEPTS)]
    shuffled = lambda keyfun: sorted(names, key=lambda n: (-keyfun(n), rng.random()))   # ties broken at random

    count, unique = {n: 0 for n in names}, {n: set() for n in names}
    for r in rows:
        name = r["retrieved"][0]["section"]
        count[name] += 1
        unique[name].add(r["student_id"])

    def composite(weights):
        report = compute_confusion(rows, quizzes, attempts, oral, weights)
        score = {c.concept: c.score for c in report.concepts}
        return shuffled(lambda n: score.get(n, 0.0))

    no_quiz = dict(DEFAULT_WEIGHTS, quiz=0.0)
    quiz_only = {name: 0.0 for name in DEFAULT_WEIGHTS} | {"quiz": 1.0}
    return {
        "question count": shuffled(lambda n: count[n]),
        "unique students": shuffled(lambda n: len(unique[n])),
        "quiz only": composite(quiz_only),
        "composite, no quiz": composite(no_quiz),
        "composite": composite(None),
    }


def evaluate(size: int, strength: float, classes: int, quiz_rate: float = 0.8) -> dict:
    precision = {}
    popular_in_top = {}
    for seed in range(classes):
        rows, quizzes, attempts, oral, confusing, popular = simulate(size, strength, seed, quiz_rate)
        for method, ranked in rankings(rows, quizzes, attempts, oral, random.Random(seed)).items():
            precision.setdefault(method, []).append(len(set(ranked[:TOP]) & confusing) / TOP)
            popular_in_top.setdefault(method, []).append(popular in ranked[:TOP])
    return {m: (sum(p) / classes, sum(popular_in_top[m]) / classes) for m, p in precision.items()}


def main() -> None:
    classes = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    print(f"{classes} simulated classes per setting; {CONCEPTS} concepts, {CONFUSING} truly confusing, 1 merely popular.")
    print("Cells show: precision@2 / how often the merely popular concept is in the top 2.\n")
    settings = [
        (0.25, 0.8, "weak effect of confusion on behaviour, 80% of students take each quiz"),
        (0.5, 0.8, "moderate effect, 80% take each quiz"),
        (1.0, 0.8, "strong effect, 80% take each quiz"),
        (0.5, 0.2, "moderate effect, only 20% take each quiz (few quiz results)"),
    ]
    for strength, quiz_rate, label in settings:
        print(label)
        for size in (12, 24, 48, 100):
            result = evaluate(size, strength, classes, quiz_rate)
            line = " | ".join(f"{m}: {p:.2f} / {d:.0%}" for m, (p, d) in result.items())
            print(f"  class of {size:3}: {line}")
        print()


if __name__ == "__main__":
    main()
