"""
Labelled example messages for the learned router.

Routes:
  doubt       a question about the course, or anything else the notes should answer
  notes       wants study notes / a summary / a cheat sheet written from the material
  explain     wants a concept taught (simply, step by step, in depth, with an analogy)
  quiz        wants to be tested
  progress    asks for the STATUS of their own learning (scores, strong/weak topics)
  study_next  asks for GUIDANCE on what to study or revise

TRAIN is used to fit the classifier. TEST is held out: it is written separately
with different phrasings, includes messages that rule-based routing gets wrong
as well as ones it gets right, and is only used to measure accuracy.
Both sets were written by the project authors, not collected from students, so
accuracy on them says how well the router generalises to new wording, not how
it will behave on real students.
"""

TRAIN = {
    "doubt": [
        "What is the difference between ACID and BASE?",
        "Explain the ACID properties",
        "Why do we use read replicas in RDS?",
        "How does Spark recover a lost partition?",
        "Define OLTP",
        "what is amazon aurora",
        "Is Multi-AZ the same as a read replica?",
        "When should I use a NoSQL database?",
        "What does BASE stand for?",
        "Can RDS take automatic backups?",
        "How does YARN client mode differ from cluster mode?",
        "what is lineage in spark",
        "Which database engines does RDS support?",
        "Why is eventual consistency acceptable?",
        "What is a data warehouse?",
        "Tell me about Amazon RDS Performance Insights",
        "Does Multi-AZ improve read performance?",
        "what is the use of a hadoop cluster",
        "Difference between OLTP and OLAP",
        "What is big data",
        "What is a Kubernetes pod?",
        "When is assignment 2 due?",
        "Is Spark included in the final exam?",
        "Who wrote the textbook for this course?",
        "What are the professor's office hours?",
        "How many marks is the midterm worth?",
        "What is machine learning?",
        "What is the capital of France?",
        "Explain how read replicas work",
        "Explain Multi-AZ deployment",
        "Explain what a partition is in Spark",
        "Can you explain the CAP theorem?",
        "Describe the architecture of Amazon RDS",
        "What is the purpose of the YARN resource manager?",
        "How are transactions isolated from each other?",
        "What is atomicity?",
        "Why was the BASE model introduced after ACID?",
        "Where are RDS backups stored?",
        "Can I scale an RDS instance without downtime?",
        "What is a relational database?",
        "How does Spark differ from Hadoop MapReduce?",
        "what are read replicas used for",
        "Is DynamoDB a relational database?",
        "What are the benefits of Amazon RDS?",
        "How many read replicas can I create?",
        "What is a primary key?",
        "Tell me about NoSQL databases",
        "What is the role of the driver program in Spark?",
        "How does RDS monitoring work?",
        "what is durability in a database",
        "Why is OLAP used for data warehouses?",
        "Which one is faster, OLTP or OLAP?",
        "What is the submission format for the lab report?",
        "Will there be a makeup class this week?",
        "Is attendance compulsory?",
        "What is the syllabus for module 4?",
        "How is the quiz graded?",
        "What is a unit test?",
        "How do transactions make progress through a commit?",
        "What is the weather like today?",
        "Who invented the relational model?",
        "What are RDD transformations?",
        "How does automatic failover work in RDS?",
        "what is a data lake",
        "What does soft state mean in BASE?",
        "Is the final exam open book?",
        "What is a standby instance?",
        "Why is Spark faster than MapReduce?",
        "What is SQL used for?",
        "Describe how backups are scheduled in RDS",
        "Where can I find the lecture notes?",
        "Are the notes updated for this semester?",
        "Who prepared the course notes?",
        "Is this topic covered in the notes?",
    ],
    "explain": [
        "Explain BASE simply",
        "explain ACID in simple terms",
        "ELI5 read replicas",
        "explain Spark lineage like I'm five",
        "can you explain OLAP step by step",
        "walk me through how Multi-AZ failover works",
        "give me an intuition for eventual consistency",
        "explain YARN for a beginner",
        "break down the ACID properties for me",
        "I don't get BASE, can you explain it more simply",
        "teach me about RDS backups from scratch",
        "explain Aurora in detail",
        "give me a detailed explanation of OLTP vs OLAP",
        "go in depth on Spark architecture",
        "use an analogy to explain read replicas",
        "make read replicas easy to understand",
        "I'm confused about Multi-AZ, explain it like I'm a beginner",
        "can you simplify the idea of lineage",
        "step by step, how does a transaction commit",
        "help me understand eventual consistency",
        "explain NoSQL in plain language",
        "explain data warehouses to me slowly",
        "give me a beginner friendly explanation of RDS",
        "walk me through Spark's execution model",
        "explain partitions in simple words",
        "I need a thorough explanation of isolation levels",
        "can you explain durability with an everyday example",
        "describe BASE step by step",
        "explain the CAP theorem in an easy way",
        "teach me OLTP from the basics",
        "give me the intuition behind atomicity",
        "explain failover in depth",
        "simply put, how do read replicas work",
        "explain RDS to someone who knows nothing about databases",
        "detailed walkthrough of YARN cluster mode please",
        "explain it to me like I'm 5: what is a database",
        "help me get my head around lineage, start from the basics",
        "make ACID simple for me",
        "break Spark architecture down step by step",
        "explain consistency models in more depth",
    ],
    "quiz": [
        "quiz me on RDS",
        "test my knowledge of Spark",
        "give me 5 questions on ACID",
        "mcqs on OLTP",
        "practice questions for BASE",
        "I want to practice read replicas",
        "can you test me on Multi-AZ",
        "make a quiz about YARN",
        "quiz me",
        "test me",
        "give me something to practice",
        "self test on databases",
        "check if I understand OLAP",
        "ask me questions about lineage",
        "let's do a quick quiz",
        "generate a quiz on Aurora",
        "quiz me on consistency models",
        "I'd like some practice problems on transactions",
        "test me on the Spark module",
        "can I get a few MCQs on backups",
        "give me a quiz on NoSQL",
        "practice problems on data warehouses please",
        "ask me a few questions to see what I remember",
        "create a short test on RDS",
        "quiz me on what I just learned",
        "I want to be tested on failover",
        "write me some questions on partitions",
        "set me a quiz",
        "give me a mock test on Module 4",
        "multiple choice questions on isolation please",
        "let me practice OLTP vs OLAP",
        "test my understanding of eventual consistency",
        "quick quiz on Spark architecture",
        "I need practice on ACID",
        "can you quiz me on read replicas and Multi-AZ",
        "give me ten questions about databases",
        "start a quiz",
        "quiz on lineage",
        "evaluate my knowledge of RDS with a few questions",
        "make me a practice test",
    ],
    "progress": [
        "how am I doing",
        "show my progress",
        "what are my weak topics",
        "which topics am I strong in",
        "my scores so far",
        "how have I performed on quizzes",
        "show my results",
        "am I improving",
        "where do I stand",
        "give me my performance summary",
        "what topics have I mastered",
        "my quiz history",
        "what is my current status",
        "how did I score",
        "show me my strengths and weaknesses",
        "what are my strong areas",
        "how many questions have I asked",
        "display my learning progress",
        "what is my score on RDS",
        "how well do I know the material so far",
        "show my performance",
        "my results please",
        "am I doing well in this course",
        "which topics am I struggling in",
        "report on my progress",
        "what have I learned so far",
        "how are my quiz marks",
        "show how I'm trending",
        "what are my weakest topics right now",
        "tell me about my progress",
        "my learning summary",
        "what's my accuracy on quizzes",
        "overview of my scores",
        "which topics have I covered",
        "how is my preparation going",
    ],
    "study_next": [
        "what should I study next",
        "what should I revise before the exam",
        "help me improve my weak areas",
        "make a study plan for me",
        "what do I focus on now",
        "which topic should I work on next",
        "teach me my weakest topic",
        "what should I learn first",
        "recommend what to study",
        "I have an exam soon, what should I revise",
        "what's next for me",
        "help me revise",
        "what should I work on",
        "suggest a topic for me to study",
        "plan my revision",
        "where should I put my effort",
        "what is the most important thing for me to review",
        "guide me through what to study next",
        "help me prepare for the test",
        "tell me what to study today",
        "which chapter should I read next",
        "what topics need my attention",
        "I'm not sure what to study, help me",
        "give me a study roadmap",
        "pick a topic for me to learn",
        "help me strengthen my weak topics",
        "what should I study tonight",
        "what to focus on before the exam",
        "recommend something for me to revise",
        "decide what I should study next",
        "I have two hours, what should I study",
        "help me catch up on what I am missing",
        "which areas do I need to improve",
        "build me a revision schedule",
        "teach me what I need most",
    ],
    "notes": [
        "make notes on ACID",
        "generate notes for Spark architecture",
        "create revision notes on RDS",
        "write short notes about OLTP vs OLAP",
        "I need study notes on NoSQL",
        "prepare notes on BASE",
        "notes on Multi-AZ please",
        "can you make me notes on eventual consistency",
        "revision notes for the exam on transactions",
        "short notes on YARN",
        "bullet point notes on Aurora",
        "make a one page summary of RDS",
        "generate a study sheet for ACID and BASE",
        "I want notes with definitions and examples on partitions",
        "download notes on Spark as a pdf",
        "pdf notes for data warehouses",
        "prepare a handout on failover",
        "write heading wise notes on NoSQL",
        "summarize read replicas",
        "summarise the ACID model",
        "give me a cheat sheet for databases",
        "turn lineage into short notes",
        "notes for Module 4",
        "make simple notes on data lakes",
        "create a summary of consistency models",
        "I want a quick summary of Spark architecture",
        "write up notes on isolation levels",
        "generate subheading wise notes on RDS backups",
        "notes about the CAP theorem please",
        "compile notes on OLAP",
        "give me concise notes on partitions",
        "put together a study guide for transactions",
        "short revision notes on Aurora",
        "make me notes with definition, use case and bullet points",
        "can I get notes on Hadoop",
        "create exam notes for NoSQL",
        "summary notes on Multi-AZ",
    ],
}

TEST = {
    "doubt": [
        "How do read replicas stay in sync with the primary database?",
        "What are the four properties in ACID?",
        "why is BASE called a relaxed model",
        "Does Spark keep data in memory or on disk?",
        "What problem does Multi-AZ solve?",
        "Which AWS service would I use for a relational database?",
        "is DynamoDB relational",
        "Can you tell me what a partition is in Spark?",
        "What happens to my data if the primary instance fails?",
        "how is OLAP different from a normal database",
        "What is the role of the cluster manager in Spark?",
        "Why can't NoSQL databases guarantee ACID?",
        "when is the next lecture",
        "How will the final exam be graded?",
        "How is the quiz scored in this course?",
        "What is a test case in software engineering?",
        "Who is teaching this course?",
        "How does a transaction progress through the commit phase?",
        "Which topics are covered in module 4?",
        "what are the benefits of using managed databases",
        "Are these notes enough to pass the exam?",
        "Where do I download last year's notes?",
    ],
    "explain": [
        "Could you explain eventual consistency in plain English?",
        "Explain read replicas to me like I'm new to this",
        "I keep mixing up ACID and BASE, can you go through them slowly?",
        "Give me a thorough, detailed walkthrough of Spark's architecture",
        "Please simplify how Multi-AZ failover works",
        "Make the concept of lineage easy to grasp",
        "Can you give me an analogy for RDS backups?",
        "explain OLAP versus OLTP in depth",
        "Break YARN client mode down step by step",
        "Describe how Aurora works, but keep it beginner friendly",
        "I'm lost on partitions, help me understand them from the basics",
        "in simple words, what is a data warehouse",
        "Teach me eventual consistency from scratch",
        "Walk through what happens during an RDS failover",
        "give me the intuition behind ACID",
        "Dumb it down for me: what is BASE?",
    ],
    "quiz": [
        "Can you quiz me on database consistency?",
        "I'd like to be tested on Spark",
        "Give me ten practice questions about RDS",
        "Let me try a few MCQs on OLTP vs OLAP",
        "Test what I know about read replicas",
        "Make me a short quiz",
        "Do you have any practice problems on lineage?",
        "I want to check my understanding of Multi-AZ with some questions",
        "Quiz time! Aurora",
        "Throw some questions at me about ACID",
        "Could I get a self-test on YARN?",
        "Create 5 multiple choice questions on BASE",
        "Examine me on the Spark module",
        "Test my knowledge, please",
        "Ask me something about RDS backups",
        "give me a pop quiz",
    ],
    "progress": [
        "How have I been doing lately?",
        "Show me my quiz scores",
        "Which topics am I good at?",
        "Where am I weak?",
        "Give me a summary of my performance",
        "Have I improved since last week?",
        "What's my average score?",
        "List my strong and weak areas",
        "How many quizzes have I taken?",
        "What do my results look like?",
        "Tell me how I'm performing",
        "Show my learning progress",
        "Which topics have I mastered so far?",
        "how did I do on my last quiz",
    ],
    "study_next": [
        "What should I focus on this week?",
        "Tell me what to revise before the test",
        "Where should I start studying?",
        "Help me fix my weak topics",
        "Plan my revision for me",
        "What topic should I tackle next?",
        "I have limited time, what's most important for me to review?",
        "Suggest what I should learn next",
        "Teach me the topic I'm worst at",
        "What's the best use of my study time right now?",
        "Which area should I improve first?",
        "Guide me on what to study",
        "Recommend a topic for me to work on",
        "Give me a revision plan",
    ],
    "notes": [
        "Can you put together some notes on database consistency?",
        "I'd like revision notes for Spark lineage",
        "Summarize the ACID properties for me",
        "Make me a cheat sheet on RDS features",
        "Notes on read replicas, please",
        "Create a PDF of notes on OLTP and OLAP",
        "Give me short, heading-wise notes about Aurora",
        "Write up a study guide for Multi-AZ",
        "Prepare quick notes: BASE model",
        "Turn the Spark module into notes",
        "Generate notes with definitions and use cases for NoSQL",
        "Condense the topic of eventual consistency into notes",
        "I need a one-page summary of YARN",
        "Compile notes on transactions for the exam",
    ],
}

ROUTES = list(TRAIN)
